// Demo data — used when Supabase is not configured
// Empresas ativas: OF (Original Fotografia), FS (Forme Seguro), GP (Gestão Pessoal)
export const DEMO_DATA = {
  empresas: [
    { id:'of', nome:'Original Fotografia', sigla:'OF', descricao:'Estudio & Eventos Visuais', cor:'#f59e0b', rgb:'245,158,11', score:52, status:'Turnaround', status_cor:'#f59e0b', faturamento:28000, meta:35000, resultado:4200, inadimplencia:8.7, crescimento:-4.2, drive_url:'https://drive.google.com/drive/folders/of-orion' },
    { id:'fs', nome:'Forme Seguro', sigla:'FS', descricao:'Fundos de Formatura Premium', cor:'#8b5cf6', rgb:'139,92,246', score:65, status:'Lancamento', status_cor:'#06b6d4', faturamento:15000, meta:50000, resultado:8500, inadimplencia:0, crescimento:50, drive_url:'https://drive.google.com/drive/folders/fs-orion' },
    { id:'gp', nome:'Gestao Pessoal', sigla:'GP', descricao:'Patrimonio & Financas Pessoais', cor:'#ec4899', rgb:'236,72,153', score:75, status:'Saudavel', status_cor:'#10b981', faturamento:0, meta:0, resultado:0, inadimplencia:0, crescimento:0, drive_url:'https://drive.google.com/drive/folders/gp-orion' },
  ],
  kpis: [
    { empresa_id:'of', icone:'👥', label:'Clientes Ativos', valor:'22 / 30', ordem:1 },
    { empresa_id:'of', icone:'📊', label:'Margem Liquida', valor:'15%', ordem:2 },
    { empresa_id:'of', icone:'🚨', label:'Inadimplencia', valor:'8,7%', ordem:3 },
    { empresa_id:'of', icone:'🏢', label:'Custo Fixo', valor:'R$ 18,5k/mes', ordem:4 },
    { empresa_id:'fs', icone:'🎓', label:'Fundos Gerenciados', valor:'3 turmas', ordem:1 },
    { empresa_id:'fs', icone:'💰', label:'Capital Gerenciado', valor:'R$ 420k', ordem:2 },
    { empresa_id:'fs', icone:'✅', label:'Inadimplencia', valor:'0%', ordem:3 },
    { empresa_id:'fs', icone:'🚀', label:'Pipeline', valor:'5 turmas', ordem:4 },
    { empresa_id:'gp', icone:'🏦', label:'Patrimonio Estimado', valor:'R$ 1,2M', ordem:1 },
    { empresa_id:'gp', icone:'💰', label:'Renda Total', valor:'R$ 52k/mes', ordem:2 },
    { empresa_id:'gp', icone:'📈', label:'Investimentos', valor:'R$ 380k', ordem:3 },
    { empresa_id:'gp', icone:'🎯', label:'Taxa de Poupanca', valor:'42%', ordem:4 },
  ],
  okrs: [
    { empresa_id:'of', objetivo:'Reduzir inadimplencia para 4%', progresso:35 },
    { empresa_id:'of', objetivo:'Atingir 30 clientes ativos', progresso:73 },
    { empresa_id:'of', objetivo:'Lancar pacote corporativo', progresso:20 },
    { empresa_id:'fs', objetivo:'Fechar 12 contratos em 2026', progresso:25 },
    { empresa_id:'fs', objetivo:'Atingir R$ 2M gerenciados', progresso:21 },
    { empresa_id:'fs', objetivo:'Lancar app Forme Digital', progresso:10 },
    { empresa_id:'gp', objetivo:'Atingir R$ 1,5M patrimonio', progresso:80 },
    { empresa_id:'gp', objetivo:'Investir R$ 10k/mes', progresso:65 },
    { empresa_id:'gp', objetivo:'Quitar financiamento imovel', progresso:45 },
  ],
  tarefas: [
    { id:'5', titulo:'Cobrancas — 3 clientes atrasados', empresa_id:'of', prioridade:'alta', status:'todo' },
    { id:'6', titulo:'Reuniao equipe — corte de custos', empresa_id:'of', prioridade:'alta', status:'todo' },
    { id:'7', titulo:'Calendario de ensaios Q2', empresa_id:'of', prioridade:'media', status:'todo' },
    { id:'8', titulo:'Revisao contrato fornecedor', empresa_id:'of', prioridade:'media', status:'done' },
    { id:'9', titulo:'Fechar UNIFENAS — Medicina 2026', empresa_id:'fs', prioridade:'alta', status:'todo' },
    { id:'10', titulo:'Proposta para UNIFAL', empresa_id:'fs', prioridade:'alta', status:'todo' },
    { id:'11', titulo:'Configurar agente IA WhatsApp', empresa_id:'fs', prioridade:'media', status:'todo' },
    { id:'12', titulo:'Planilha fundos ativos', empresa_id:'fs', prioridade:'media', status:'done' },
    { id:'17', titulo:'Declaracao IRPF 2026', empresa_id:'gp', prioridade:'alta', status:'todo' },
    { id:'18', titulo:'Revisar carteira de investimentos', empresa_id:'gp', prioridade:'media', status:'todo' },
    { id:'19', titulo:'Renovar seguro de vida', empresa_id:'gp', prioridade:'media', status:'todo' },
    { id:'20', titulo:'Planejamento viagem familia', empresa_id:'gp', prioridade:'baixa', status:'todo' },
  ],
  contratos: [
    { empresa_id:'of', nome:'Parceria Evento Casa Casada', valor:'R$ 3.500/evento', status:'ativo', vencimento:'Dez/2026' },
    { empresa_id:'of', nome:'Cliente Corporativo XYZ', valor:'R$ 1.800/mes', status:'inadim', vencimento:'Mai/2026' },
    { empresa_id:'fs', nome:'Fundo UNIFENAS Med 2026', valor:'R$ 5.000/mes', status:'ativo', vencimento:'Dez/2026' },
    { empresa_id:'fs', nome:'Fundo UNILAVRAS Med 2025', valor:'R$ 6.200/mes', status:'ativo', vencimento:'Jun/2025' },
    { empresa_id:'gp', nome:'Financiamento Imovel — CEF', valor:'R$ 2.100/mes', status:'ativo', vencimento:'Dez/2031' },
    { empresa_id:'gp', nome:'Previdencia Privada PGBL', valor:'R$ 1.500/mes', status:'ativo', vencimento:'Vitalicio' },
  ],
  riscos: [
    { empresa_id:'of', descricao:'Sazonalidade — queda Q1 e Q3 todo ano', nivel:'alto' },
    { empresa_id:'of', descricao:'Equipamento principal precisa revisao urgente', nivel:'medio' },
    { empresa_id:'fs', descricao:'Concorrencia de bancos tradicionais nos fundos', nivel:'medio' },
    { empresa_id:'fs', descricao:'Dependencia total de captacao via indicacao', nivel:'alto' },
    { empresa_id:'gp', descricao:'Concentracao de renda em empresas proprias', nivel:'alto' },
    { empresa_id:'gp', descricao:'Falta de diversificacao internacional', nivel:'medio' },
  ],
  decisoes: [
    { empresa_id:'of', descricao:'Reestruturacao completa de precificacao', data:'Mar/2026' },
    { empresa_id:'of', descricao:'Definir nicho: corporativo vs social', data:'Abr/2026' },
    { empresa_id:'fs', descricao:'Contratar comercial dedicado para novas turmas', data:'Abr/2026' },
    { empresa_id:'fs', descricao:'Criar landing page Forme Seguro', data:'Mar/2026' },
    { empresa_id:'gp', descricao:'Aportar em FII — MXRF11', data:'Mar/2026' },
    { empresa_id:'gp', descricao:'Contratar assessor de investimentos', data:'Abr/2026' },
  ],
  crmLeads: [
    { empresa_id:'of', fase:'Lead', nome:'Turma Direito UFMG 2027', valor:'Projeto 3 anos' },
    { empresa_id:'of', fase:'Lead', nome:'Evento Empresa XYZ', valor:'R$ 4.500' },
    { empresa_id:'of', fase:'Proposta', nome:'Formatura Medicina BH', valor:'Projeto 4 anos' },
    { empresa_id:'of', fase:'Fechado', nome:'Casamento Silva', valor:'R$ 8.000' },
    { empresa_id:'fs', fase:'Lead', nome:'UNIFAL Medicina 2027', valor:'Projeto 5 anos' },
    { empresa_id:'fs', fase:'Lead', nome:'UFLA Medicina 2026', valor:'Projeto 4 anos' },
    { empresa_id:'fs', fase:'Proposta', nome:'UNIFENAS Odonto 2026', valor:'Projeto 3 anos' },
    { empresa_id:'fs', fase:'Negociacao', nome:'UNIMONTES Med 2026', valor:'Projeto 4 anos' },
    { empresa_id:'fs', fase:'Fechado', nome:'UNIFENAS Med 2026', valor:'R$ 5.000/mes' },
  ]
}
